#!/usr/bin/env bash

SCRIPT_DIR=$(realpath "$(dirname "${0}")")
VENV_DIR="${SCRIPT_DIR}/.venv"
SRC_DIR="${SCRIPT_DIR}/src"
MANAGE_PY="${SRC_DIR}/manage.py"
ARGS=()


usage() {
cat << EOF
Runs either app or tests.

Usage:
    ${0} [COMMANDS] [OPTIONS] [EXTR_ARGS]

Commands:
    test           Run tests
    e2e-test       Run e2e tests

Options:
    --dev          Run dev server
    --profile FILE Load wall profiles into database from file before run server
    --workers NUM  Set the number of workers for multi process case (default: 1)
    --debug        Set bash 'x' option
    --help         Shows help message

For extra Django CLI use 'python3 ${MANAGE_PY}'
EOF
}

set -eu

ensure_env() {
    if [ -d "${VENV_DIR}" ]; then
        source "${VENV_DIR}/bin/activate"
    else
        python3 -m venv "${VENV_DIR}" && \
            source "${VENV_DIR}/bin/activate" && \
            pip3 install -r "${SCRIPT_DIR}/requirements.txt"

        if [ "${?}" -ne 0 ]; then 
            rm -rf "${VENV_DIR}"
            echo -e "\e[31mVirtual env setup error\e[0m"
            exit 1
        fi 
    fi    
}

while [ "${#}" -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            exit
            ;;

        test)
            TEST=1
            ;;

        e2e-test)
            E2E_TEST=1
            ;;

        --dev)
            DEV=1
            ;;

        --profile)
            shift
            WALLS_FILE="${1}"
            ;;

        --workers)
            shift
            WORKERS_NUM="${1}"
            ;;

        --debug)
            set -x
            ;;

        *)
            ARGS+=("${1}")
            ;;
    esac
    
   shift
done

APP_CONAINER_NAME=e2e-app-instance
E2E_CONTAINER_NAME=e2e-tests-instance

remove_containers() {
    docker stop "${APP_CONAINER_NAME}" &>/dev/null || true
    docker stop "${E2E_CONTAINER_NAME}" &>/dev/null || true
    docker rm "${APP_CONAINER_NAME}" &>/dev/null || true
    docker rm "${E2E_CONTAINER_NAME}" &>/dev/null || true
}

clean_up() {
    if [ -n "${REMOVED+x}" ]; then
        return
    fi
    REMOVED=1
    popd &> /dev/null
    remove_containers    
}

on_exit() {
    clean_up
}

on_error() {
    clean_up
}

trap on_exit EXIT
trap 'on_error ${?} ${LINENO}' ERR

pushd "${SCRIPT_DIR}" &> /dev/null

if [ -n "${TEST+x}" ]; then
    ensure_env
    python3 "${MANAGE_PY}" makemigrations
    python3 "${MANAGE_PY}" migrate
    cd "${SRC_DIR}" && DEPS_LOG_LEVEL=ERROR pytest "${ARGS[@]}"
    exit 0
fi

if [ -n "${E2E_TEST+x}" ]; then
    echo -e "\e[36mRunning e2e tests...\e[0m"
    docker compose build

    # docker compose run --name "${APP_CONAINER_NAME}" --detach wall_tracker /app/run --debug
    # docker compose run --name "${E2E_CONTAINER_NAME}" e2e_tests pytest test_app_first_part.py -k test_must_return_404_not_if_no_profiles_at_all "${ARGS[@]}"
    # remove_containers

    # docker compose run --name "${APP_CONAINER_NAME}" --detach wall_tracker /app/run --profile /app/wall-profiles1.txt
    # docker compose run --name "${E2E_CONTAINER_NAME}" e2e_tests pytest test_app_first_part.py -k 'not test_must_return_404_not_if_no_profiles_at_all' "${ARGS[@]}"
    # remove_containers

    docker compose run --name "${APP_CONAINER_NAME}" --detach wall_tracker /app/run --debug
    docker compose run --name "${E2E_CONTAINER_NAME}" e2e_tests pytest test_app_mp.py -k test_must_return_404_not_if_no_profiles_at_all "${ARGS[@]}"
    remove_containers

    docker compose run --name "${APP_CONAINER_NAME}" --detach wall_tracker /app/run --profile /app/wall-profiles2.txt --workers 10
    docker compose run --name "${E2E_CONTAINER_NAME}" e2e_tests pytest test_app_mp.py -k 'not test_must_return_404_not_if_no_profiles_at_all' "${ARGS[@]}"
    remove_containers
    exit 0
fi

ensure_env
python3 "${MANAGE_PY}" makemigrations
python3 "${MANAGE_PY}" migrate

if [ -n "${WALLS_FILE+x}" ]; then
    python3 "${MANAGE_PY}" import_profile "${WALLS_FILE}"
fi

if [ -n "${WORKERS_NUM+x}" ]; then
    python3 "${MANAGE_PY}" teams_num "${WORKERS_NUM}"
fi

if [ -n "${DEV+x}" ]; then
    python3 "${MANAGE_PY}" runserver "${ARGS[@]}"
else 
    cd "${SRC_DIR}" && uvicorn --host '0.0.0.0' "${ARGS[@]}" thewall.asgi:application
fi 
