# Generated by Django 5.1 on 2024-08-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_tracker_mp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.IntegerField()),
            ],
        ),
    ]
