# Generated by Django 5.1 on 2024-08-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_tracker_mp', '0002_teamsnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamsNumber',
        ),
        migrations.DeleteModel(
            name='WallProfile',
        ),
    ]
